use serde::Serialize;

#[derive(Serialize, Debug)]
pub struct ProData {
    pub game_num: i32,
    pub kyoku_num: i32,
    pub point: f64,
    pub avg_point: f64,
    pub agari_rate: f64,
    pub houjuu_rate: f64,
    pub tsumo_rate: f64,
    pub dama_rate: f64,
    pub ryukyoku_rate: f64,
    pub ryukyoku_tenpai_rate: f64,
    pub furo_rate: f64,
    pub richi_rate: f64,
    pub avg_agari_turn: f64,
    pub avg_agari_score: f64,
    pub avg_houjuu_score: f64,
    pub avg_rank: f64,
    pub blown_rate: f64,
    pub avg_blown_score: f64,
    pub ron_rate: f64,
    pub first_rate: f64,
    pub second_rate: f64,
    pub third_rate: f64,
    pub fourth_rate: f64,
    pub richi_agari_rate: f64,
    pub richi_houjuu_rate: f64,
    pub richi_tsumo_rate: f64,
    pub avg_richi_agari_score: f64,
    pub richi_ryukyoku_rate: f64,
    pub avg_richi_turn: f64,
    pub avg_richi_dora: f64,
    pub richi_first_rate: f64,
    pub richi_chase_rate: f64,
    pub richi_chased_rate: f64,
    pub ippatsu_rate: f64,
    pub uradora_rate: f64,
    pub highest_score: i32,
    pub lowest_score: i32,
}

impl ProData {
    pub fn empty() -> Self {
        ProData {
            game_num: 0,
            kyoku_num: 0,
            point: 0.0,
            avg_point: 0.0,
            agari_rate: 0.0,
            houjuu_rate: 0.0,
            tsumo_rate: 0.0,
            dama_rate: 0.0,
            ryukyoku_rate: 0.0,
            ryukyoku_tenpai_rate: 0.0,
            furo_rate: 0.0,
            richi_rate: 0.0,
            avg_agari_turn: 0.0,
            avg_agari_score: 0.0,
            avg_houjuu_score: 0.0,
            avg_rank: 0.0,
            blown_rate: 0.0,
            avg_blown_score: 0.0,
            ron_rate: 0.0,
            first_rate: 0.0,
            second_rate: 0.0,
            third_rate: 0.0,
            fourth_rate: 0.0,
            richi_agari_rate: 0.0,
            richi_houjuu_rate: 0.0,
            richi_tsumo_rate: 0.0,
            avg_richi_agari_score: 0.0,
            richi_ryukyoku_rate: 0.0,
            avg_richi_turn: 0.0,
            avg_richi_dora: 0.0,
            richi_first_rate: 0.0,
            richi_chase_rate: 0.0,
            richi_chased_rate: 0.0,
            ippatsu_rate: 0.0,
            uradora_rate: 0.0,
            highest_score: 0,
            lowest_score: 0,
        }
    }
}
